### ISSUE TITLE
Export in Real Time Timeout

### ISSUE THREAD

**Issue by basselalaraaj** [EmicoEcommerce/Magento2TweakwiseExport-archived#29]
Issue Brief
--
Exporting a lot products through the realtime function is giving timeout error.

Environment
--
- [x] PHP Version: PHP 7.0
- [x] Magento Version: 2.1.9
- [x] Magento Enterprise: (yes)
- [x] Tweakwise Export Version: 1.0.8
- [x] Magento Deploy Mode: (production)

Steps to reproduce
--
1. import in magento 80.000 products.
2. run import task in tweakwise.

Actual result
--
Time out error, Tweakwise does not contain product information.

Expected result
--
Tweakwise contains all product information.

**Comment by Fgruntjes** [comment]
Hello,

This is due to your webserver settings. When export is set to real time the export will start when the url is requested, with allot of products this can take a while and run into your webserver or PHP timeout. It is recommended to setup a cronjob using the console export and disable the real time setting.

```bash
php bin/magento tweakwise:export
```

**Comment by basselalaraaj** [comment]
@Fgruntjes and if we want to use your module for our customers, we have to create a cronjob for every customer? why not adding  a cronjob in your module as Magento 1 had? so that your module is always plug and play.

**Comment by Fgruntjes** [comment]
@basselalaraaj This is on our todo list but currently does not have a very high priority. Also created a github issue for it #30

We are happy to accept a pull request if you have the time to fix the issue.
