### ISSUE TITLE
Export not complete. Storeviews missing.

### ISSUE THREAD

**Issue by EduardSelles** [EmicoEcommerce/Magento2TweakwiseExport-archived#62]
Issue Brief
--
The export module generates an export file. Not all storeviews are included in this file.

Environment
--
- [ ] Magento Version: M2 
- [ ] Tweakwise Export Version: latest release v1.3.1

Steps to reproduce
--
1. goto https://tweakwise2-ee.emico.nl/tweakwiseadmin
2. Make sure you have several storeviews (module Catalog > Categories)
3. Start making export file (module Stores > Configuration > Catalog > Tweakwise > Export
4. goto https://navigator.tweakwise.com, instance "Test Magento 2 Enterprise" (Emico only)
5. check categorie tree in navigator. Module Catalogus > Categorien.

Actual result
--
Only one storeview available in Tweakwise

Expected result
--
All (three) store views available in Tweakwise

**Comment by edwinljacobs** [comment]
Hello,

The issue lies with a performance fix we released a few weeks in the past, this fix drastically reduced the amount of memory consumed by the export. Unfortunately there is an error in the fix which happens at 500 categories or more (500 being a batch limit) and there are multiple store views having the same root category. The issue lies in the EavIterator Class which keeps track of state, in this case entity ids for the current batch, this state is not properly purged after the export finishes for the given store. This results in an empty category list for the next run.

We have a fix for this in branch: issue/98557-missing-store-views here we simply purge entity ids and this is enough. If someone experiences this issue (this affects 1.3.0 and above) one could try to include this fix by:
composer require emico/tweakwise-export "dev-issue/98557-missing-store-views" which is based on the latest release + this fix

Do not do this on a production environment, test this first!

if this throws some version error then one can require emico/tweakwise-export "dev-issue/98557-missing-store-views as {version-number}".

We understand that this is very frustrating and we will release this fix soon.

With kind regards

**Comment by jasperzeinstra** [comment]
I also ran in to this issue and found the same fix as in the issue branch before I noticed that it was already fixed here. Als notice that having bundle / configurable products with a lot of child products can give errors https://github.com/EmicoEcommerce/Magento2TweakwiseExport/issues/63.

**Comment by edwinljacobs** [comment]
Hi,

Release v1.3.2 should take care of this.

With kind regards
